[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "ls -la dist/ || echo 'dist not found'",
  "ls -la dist/public/ || echo 'dist/public not found'"
]

[start]
cmd = "python start_server.py"
