[phases.setup]
nixPkgs = ["python311", "nodejs_20", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "python -m uvicorn server.main:app --host 0.0.0.0 --port $PORT"
