[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn server.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
